# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('source', models.CharField(blank=True, choices=[('YOUTUBE', 'YOUTUBE'), ('VIMEO', 'VIMEO')], max_length=1, null=True)),
            ],
        ),
    ]
