# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.CharField(blank=True, choices=[('YOUTUBE', 'YOUTUBE'), ('VIMEO', 'VIMEO')], max_length=7, null=True),
        ),
    ]
